pipeline {
    agent any
         tools {
            maven 'maven'
        }
    stages {

        stage('Build') {
            steps {
                script {
                    sh 'cd ./clientui'
                    sh 'mvn package'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
