pipeline {

    agent any

    stages{
        stage('Git checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/Echarji/demo.git'
            }
        }
         stage('unit test'){
             steps{
                sh 'cd clientui'
                sh 'mvn test'
             }
         }
    }
}