pipeline {
    agent any

    stages {
         tools {
            maven 'maven-3.6.3'
        }
        stage('Build') {
            steps {
                sh 'cd ./clientui'
                sh 'mvn install'
            }
        }
        stage('Test') {
            steps {
                cd 'cd ./clientui'
                sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
