name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 64.227.96.168 >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        run: |
          cat ~/.ssh/id_rsa
          ssh github@64.227.96.168 "cd /path/to/app && echo test"
